### PR TITLE
Add support for NFC card input

### PR DESCRIPTION
**Pull request by mistydemeo**
This adds support for NFC cards as an input device. The intended use is simulating contactless payment, like the IC card readers that are used in most arcades in Japan.

The IC card reader is meant to present itself as an input device, using the `EV_MSC` type and `MSC_RAW` code. I'm using this with a [homegrown program](https://github.com/mistydemeo/kensatsu), which uses the Sony PaSoRi USB reader to poll for taps and emits the appropriate events in response.

So far this mostly works, but I'm encountering a couple problems so I'm leaving the PR in a draft state. When the PaSoRi is connected and mapped, I'm seeing periodic `Error: A checksum error occoured` messages in the terminal and glitchy behaviour from the board after a card is tapped the first time - namely, the credits seem to oscillate between 0 and 1, with the board repeating the insert coin sound every time it goes back to 1. It's late and I'm tired, so I may have missed something blindingly obvious here that's causing me to do something weird on the JVS side of things. I've confirmed via `evtest` that only a single event is being sent every time the card is tapped, and no events are being sent when a card isn't tapped, and that OpenJVS's input loop only sees a single `EV_MSC` input with the correct code when a card is tapped.

I'm using the input mapping from this PR, and the following output mapping:
```
# System Buttons
CONTROLLER_BUTTON_TEST CONTROLLER_1 BUTTON_TEST SYSTEM
CONTROLLER_BUTTON_TILT CONTROLLER_1 BUTTON_TILT_1 SYSTEM

# Player One Buttons
CONTROLLER_BUTTON_START CONTROLLER_1 BUTTON_START PLAYER_1
CONTROLLER_BUTTON_SERVICE CONTROLLER_1 BUTTON_SERVICE PLAYER_1
CONTROLLER_BUTTON_UP CONTROLLER_1 BUTTON_UP PLAYER_1
CONTROLLER_BUTTON_DOWN CONTROLLER_1 BUTTON_DOWN PLAYER_1
CONTROLLER_BUTTON_LEFT CONTROLLER_1 BUTTON_LEFT PLAYER_1
CONTROLLER_BUTTON_RIGHT CONTROLLER_1 BUTTON_RIGHT PLAYER_1
CONTROLLER_BUTTON_A CONTROLLER_1 BUTTON_1 PLAYER_1
CONTROLLER_BUTTON_B CONTROLLER_1 BUTTON_2 PLAYER_1
CONTROLLER_BUTTON_C CONTROLLER_1 BUTTON_3 PLAYER_1
CONTROLLER_BUTTON_RIGHT_BUMPER CONTROLLER_1 BUTTON_4 PLAYER_1
CONTROLLER_BUTTON_COIN CONTROLLER_2 COIN PLAYER_1
```

It shouldn't cause issues to be using an input from controller 2 for player 1, right? Since the PaSoRi is a separate input device, it's not sending inputs on behalf of the first controller.

Another followup I want to do in a later PR is allow the event to specify the number of coins to insert, instead of hardcoding it to one like it is right now. The number of coins can be fetched from the value of the event, with the device sending the event responsible for deciding how much to send.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Actually, I think OpenJVS's coin insertion mechanism might just be broken right now. I went back to master, mapped coin to a button, and I'm seeing the same broken coin insertion behaviour.

**Comment by bobbydilley** [comment]
This looks awesome!
What system have you been testing with? I'm wondering if exa is the issue here as I've not had any problems with coins myself?

**Comment by mistydemeo** [comment]
It turned out to be totally self-inflicted. I'd tried to stop OpenJVS via systemd but must have failed to, so it didn't actually stop. Turns out running two instances at once causes problems! Who knew. The branch works fine so long as only one OpenJVS instance is running.

**Comment by bobbydilley** [comment]
Thanks for this, I'm excited to hopefully try it out myself at some point!

**Pull request merged**
